# ===============================
# Basic Site Configuration
# ===============================

theme: jekyll-theme-chirpy

title: Sm1l3
lang: en
timezone: Asia/Karachi

url: "https://i-am-sm1l3.github.io"
baseurl: ""

github:
  username: I-am-Sm1l3

social:
  name: Sm1l3
  links:
    - https://github.com/I-am-Sm1l3

theme_mode: dark

avatar:  assets/img/avatar.png

toc: true
paginate: 10

# ===============================
# Collections & Defaults
# ===============================

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      toc: true
      permalink: /posts/:title/

  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

# ===============================
# Markdown & Syntax Highlighting
# ===============================

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all

# ===============================
# Exclusions
# ===============================

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
